import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
// import cover from "../public/backgroundCover.png";
import Image from "next/image";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "XeroCodee",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
  
        <div className=" bg-[#C2DAFB]   h-[100vh] ">{children}</div>
      </body>
    </html>
  );
}
